#lang racket/base

(require "common.rkt"
         "interface/editor.rkt")

(provide pasteboard%/c)

(define pasteboard%/c
  (and/c
   editor<%>/c
   (class/c
    (add-selected (case->m (-> (is-a?/c snip%) any)
                           (-> real? real? (>=/c 0) (>=/c 0) any)))
    (after-delete (->m (is-a?/c snip%) any))
    (after-insert (->m (is-a?/c snip%) (maybe/c (is-a?/c snip%)) real? real? any))
    (after-interactive-move (->m (is-a?/c mouse-event%) any))
    (after-interactive-resize (->m (is-a?/c snip%) any))
    (after-move-to (->m (is-a?/c snip%) real? real? any/c any))
    (after-reorder (->m (is-a?/c snip%) (is-a?/c snip%) any/c boolean?))
    (after-resize (->m (is-a?/c snip%) (>=/c 0) (>=/c 0) any/c any))
    (after-select (->m (is-a?/c snip%) any/c any))
    (can-delete? (->m (is-a?/c snip%) boolean?))
    (can-insert? (->m (is-a?/c snip%) (maybe/c (is-a?/c snip%)) real? real? boolean?))
    (can-interactive-move? (->m (is-a?/c snip%) boolean?))
    (can-interactive-resize? (->m (is-a?/c snip%) boolean?))
    (can-move-to? (->m (is-a?/c snip%) real? real? any/c boolean?))
    (can-reorder? (->m (is-a?/c snip%) (is-a?/c snip%) any/c boolean?))
    (can-resize? (->m (is-a?/c snip%) (>=/c 0) (>=/c 0) boolean?))
    (can-select? (->m (is-a?/c snip%) any/c boolean?))
    (inner
      (after-delete (->m (is-a?/c snip%) any))
      (after-insert (->m (is-a?/c snip%) (maybe/c (is-a?/c snip%)) real? real? any))
      (after-interactive-move (->m (is-a?/c mouse-event%) any))
      (after-interactive-resize (->m (is-a?/c snip%) any))
      (after-move-to (->m (is-a?/c snip%) real? real? any/c any))
      (after-reorder (->m (is-a?/c snip%) (is-a?/c snip%) any/c boolean?))
      (after-resize (->m (is-a?/c snip%) (>=/c 0) (>=/c 0) any/c any))
      (after-select (->m (is-a?/c snip%) any/c any))
      (can-delete? (->m (is-a?/c snip%) boolean?))
      (can-insert? (->m (is-a?/c snip%) (maybe/c (is-a?/c snip%)) real? real? boolean?))
      (can-interactive-move? (->m (is-a?/c snip%) boolean?))
      (can-interactive-resize? (->m (is-a?/c snip%) boolean?))
      (can-move-to? (->m (is-a?/c snip%) real? real? any/c boolean?))
      (can-reorder? (->m (is-a?/c snip%) (is-a?/c snip%) any/c boolean?))
      (can-resize? (->m (is-a?/c snip%) (>=/c 0) (>=/c 0) boolean?))
      (can-select? (->m (is-a?/c snip%) any/c boolean?)))
    ;(change-style (->* () 
    ;                   ((maybe/c (or/c (is-a?/c style-delta%) (is-a?/c style<%>)))
    ;                    (maybe/c (is-a?/c snip%)))
    ;                   any))
    (delete (case->m (-> any)
                     (-> (is-a?/c snip%) any)))
    (do-copy (->m exact-integer? any/c any))
    (do-paste (->m exact-integer? any))
    (do-paste-x-selection (->m exact-integer? any))
    (override
      (do-copy (->m exact-integer? any/c any))
      (do-paste (->m exact-integer? any))
      (do-paste-x-selection (->m exact-integer? any)))
    (erase (->m any))
    (find-next-selected-snip (->m (maybe/c (is-a?/c snip%)) (maybe/c (is-a?/c snip%))))
    (find-snip (->*m (real? real?) ((maybe/c (is-a?/c snip%))) (maybe/c (is-a?/c snip%))))
    (get-center (->m (values real? real?)))
    (get-dragable (->m boolean?))
    (get-scroll-step (->m (>=/c 0)))
    (get-selection-visible (->m boolean?))
    (insert 
      (case->m (-> (is-a?/c snip%) any)
        (-> (is-a?/c snip%) (maybe/c (is-a?/c snip%)) real? real? any)
        (-> (is-a?/c snip%) real? real? any)
        (-> (is-a?/c snip%) (maybe/c (is-a?/c snip%)) any)))
    (interactive-adjust-mouse (->m (box/c real?) (box/c real?) any))
    (interactive-adjust-move (->m (is-a?/c snip%) (box/c real?) (box/c real?) any))
    (interactive-adjust-resize (->m (is-a?/c snip%)
                                    (box/c (>=/c 0)) 
                                    (box/c (>=/c 0))
                                    any))
    (override
      (interactive-adjust-mouse (->m (box/c real?) (box/c real?) any))
      (interactive-adjust-move (->m (is-a?/c snip%) (box/c real?) (box/c real?) any))
      (interactive-adjust-resize (->m (is-a?/c snip%)
                                      (box/c (>=/c 0)) 
                                      (box/c (>=/c 0))
                                      any)))
    (is-selected? (->m (is-a?/c snip%) boolean?))
    (lower (->m (is-a?/c snip%) any))
    (move (case->m (-> (is-a?/c snip%) real? real? any)
                   (-> real? real? any)))
    (move-to (->m (is-a?/c snip%) real? real? any))
    (no-selected (->m any))
    (on-delete (->m (is-a?/c snip%) any))
    (on-double-click (->m (is-a?/c snip%) (is-a?/c mouse-event%) any))
    (on-insert (->m (is-a?/c snip%) (maybe/c (is-a?/c snip%)) real? real? any))
    (on-interactive-move (->m (is-a?/c mouse-event%) any))
    (on-interactive-resize (->m (is-a?/c snip%) any))
    (on-move-to (->m (is-a?/c snip%) real? real? any/c any))
    (on-reorder (->m (is-a?/c snip%) (is-a?/c snip%) any/c any))
    (on-resize (->m (is-a?/c snip%) (>=/c 0) (>=/c 0) any))
    (on-select (->m (is-a?/c snip%) any/c any))
    (override
      (on-double-click (->m (is-a?/c snip%) (is-a?/c mouse-event%) any)))
    (inner
      (on-delete (->m (is-a?/c snip%) any))
      (on-insert (->m (is-a?/c snip%) (maybe/c (is-a?/c snip%)) real? real? any))
      (on-interactive-move (->m (is-a?/c mouse-event%) any))
      (on-interactive-resize (->m (is-a?/c snip%) any))
      (on-move-to (->m (is-a?/c snip%) real? real? any/c any))
      (on-reorder (->m (is-a?/c snip%) (is-a?/c snip%) any/c any))
      (on-resize (->m (is-a?/c snip%) (>=/c 0) (>=/c 0) any))
      (on-select (->m (is-a?/c snip%) any/c any)))
    (raise (->m (is-a?/c snip%) any))
    (remove (->m (is-a?/c snip%) any))
    (remove-selected (->m (is-a?/c snip%) any))
    (resize (->m (is-a?/c snip%) (>=/c 0) (>=/c 0) boolean?))
    (set-after (->m (is-a?/c snip%) (maybe/c (is-a?/c snip%)) any))
    (set-before (->m (is-a?/c snip%) (maybe/c (is-a?/c snip%)) any))
    (set-dragable (->m any/c any))
    (set-scroll-step (->m (>=/c 0) any))
    (set-selected (->m (is-a?/c snip%) any))
    (set-selection-visible (->m any/c any)))))
